### ISSUE TITLE
post/windows/gather/hashdump encoding problem

### ISSUE THREAD

**Issue by bs-arod** [rapid7/metasploit-framework#5815]
post/windows/gather/hashdump just fails with a french Windows. 

It seems it fails with the guest account which is "invité" in french.
Is there any bugfix to do on my system ? Or in metasploit ?
Thanks!

```
  meterpreter > sysinfo 
  Computer        : SRV2
  OS              : Windows 7 (Build 7601, Service Pack 1).
  Architecture    : x64
  System Language : fr_FR
  Domain          : BS
  Logged On Users : 7
  Meterpreter     : x64/win64
```

```
meterpreter > run post/windows/gather/hashdump 

[*] Obtaining the boot key...
[*] Calculating the hboot key using SYSKEY be09014[...]75e64d83...
[*] Obtaining the user list and keys...
[*] Decrypting user keys...
[*] Dumping password hints...
[...]

[*] Dumping password hashes...


Administrateur:500:aad3b435b51404eeaad3b435b51404ee:[some ntlm hash]:::
[-] Post failed: ActiveRecord::StatementInvalid PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x27 0x20
: SELECT  "metasploit_credential_publics".* FROM "metasploit_credential_publics"  WHERE "metasploit_credential_publics"."type" IN ('Metasploit::Credential::Username') AND "metasploit_credential_publics"."username" = 'invit?'  ORDER BY "metasploit_credential_publics"."id" ASC LIMIT 1
[-] Call stack:
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `async_exec'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `exec_no_cache'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `block in exec_query'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:915:in `select'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/querying.rb:36:in `find_by_sql'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/relation.rb:587:in `exec_queries'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/relation.rb:471:in `load'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/relation.rb:220:in `to_a'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/relation/finder_methods.rb:326:in `find_first'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/relation/finder_methods.rb:91:in `first'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders/relation.rb:129:in `first'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.13/lib/active_record/relation.rb:137:in `first_or_create!'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/metasploit-credential-1.0.0/lib/metasploit/credential/creation.rb:426:in `block in create_credential_public'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/metasploit-credential-1.0.0/lib/metasploit/credential/creation.rb:532:in `retry_transaction'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/metasploit-credential-1.0.0/lib/metasploit/credential/creation.rb:422:in `create_credential_public'
[-]   /home/arod/.rvm/gems/ruby-2.1.5/gems/metasploit-credential-1.0.0/lib/metasploit/credential/creation.rb:134:in `create_credential'
[-]   /opt/metasploit-framework/lib/msf/core/auxiliary/report.rb:34:in `create_credential'
[-]   /opt/metasploit-framework/modules/post/windows/gather/hashdump.rb:98:in `block in run'
[-]   /opt/metasploit-framework/modules/post/windows/gather/hashdump.rb:90:in `each'
[-]   /opt/metasploit-framework/modules/post/windows/gather/hashdump.rb:90:in `run'
```

**Comment by bcook-r7** [comment]
This was fixed in https://github.com/rapid7/metasploit-payloads/pull/100 after a couple of false-starts. Thanks!

**Comment by jvoisin** [comment]
I can still reproduce it, with the latest (27018b421c1cd7eae58e9bed46ccfd4597c44730) git version:

```ruby
meterpreter > run post/windows/gather/credentials/credential_collector 

[*] Running module against XXXXX
[+] Collecting hashes...
    Extracted: Administrateur:XXXX:XXX
[-] Post failed: ActiveRecord::StatementInvalid PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9
: SELECT  "metasploit_credential_publics".* FROM "metasploit_credential_publics" WHERE "metasploit_credential_publics"."type" IN ('Metasploit::Credential::Username') AND "metasploit_credential_publics"."username" = $1  ORDER BY "metasploit_credential_publics"."id" ASC LIMIT 1
[-] Call stack:
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:39:in `find_by_sql'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:639:in `exec_queries'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:515:in `load'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:243:in `to_a'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:127:in `first'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:159:in `first_or_create!'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/metasploit-credential-2.0.3/lib/metasploit/credential/creation.rb:426:in `block in create_credential_public'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/metasploit-credential-2.0.3/lib/metasploit/credential/creation.rb:532:in `retry_transaction'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/metasploit-credential-2.0.3/lib/metasploit/credential/creation.rb:422:in `create_credential_public'
[-]   /opt/msf/vendor/ruby/2.3.0/gems/metasploit-credential-2.0.3/lib/metasploit/credential/creation.rb:134:in `create_credential'
[-]   /opt/msf/lib/msf/core/auxiliary/report.rb:34:in `create_credential'
[-]   /opt/msf/modules/post/windows/gather/credentials/credential_collector.rb:76:in `block in run'
[-]   /opt/msf/modules/post/windows/gather/credentials/credential_collector.rb:55:in `each'
[-]   /opt/msf/modules/post/windows/gather/credentials/credential_collector.rb:55:in `run'
meterpreter > 
```

**Comment by bcook-r7** [comment]
Thanks, I'll reopen.

**Comment by bcook-r7** [comment]
Seems to be a slightly different error than before:

[-] Post failed: ActiveRecord::StatementInvalid PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9

vs

[-] Post failed: ActiveRecord::StatementInvalid PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x27 0x20

**Comment by jvoisin** [comment]
It think it's because the unsupported character is a different one.

**Comment by bwatters-r7** [comment]
This might be the same problem I'm hitting on another project where some of the DB's custom integrity checks rely on ANSI encoding or some horror-show half-encoding that I've found in other places..

**Comment by h0n3yc4k3** [comment]
@bwatters-r7 module _post/windows/gather/hashdump_ seems like fixed 🤔
<img width="701" alt="Снимок экрана 2020-03-09 в 19 06 21" src="https://user-images.githubusercontent.com/34004367/76233780-c79f8680-6239-11ea-95d3-9fcfce032612.png">
But in module _post/windows/gather/credentials/credential_collector_ I too have that problem
<img width="1208" alt="Снимок экрана 2020-03-09 в 19 22 22" src="https://user-images.githubusercontent.com/34004367/76234863-57920000-623b-11ea-8375-699b2f60b360.png">

**Comment by bwatters-r7** [comment]
It hash been more than three years, and this looks fixed... Thanks, @h0n3yc4k3
